# Form implementation generated from reading ui file 'WIndow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import base64
import glob
import os
from tkinter import Image

import requests
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 310)
        Form.setStyleSheet("QWidget{\n"
"background-color:\"#rgb(0, 0, 0)\"\n"
"}")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(90, 250, 221, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setStyleSheet("QPushButton{\n"
"        background-color:\"white\"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.click_generate_button)
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"        background-color:\"white\"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def click_generate_button(self):
        image_list=[]
        image_url = "https://github.com/hfg-gmuend/openmoji/tree/master/src/symbols/geometric"
        response = requests.get(image_url)
        if response.status_code != 200:
            print(response.status_code)
        try:
            m=response.json()
        except:    
            print("Error")
        l=[link["download_url"] for link in m]
        print(l)

       
        #os.listdir(image_url)
        

        #image = requests.get(image_url).json()
        #print(image)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "App"))
        self.pushButton.setText(_translate("Form", "Generate"))
        self.pushButton_2.setText(_translate("Form", "Group"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
